name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/fastapi-app:latest ./app

      - name: Push image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/fastapi-app:latest
